hdocker:
  image: qurius/ubuntu-cloudera-5-cm:0.1
  hostname: hdocker
  ports:
    - "7180:7180"
  expose:
    - "7182"
master:
  image: qurius/ubuntu-cloudera-5-master-node:0.1
  hostname: master
  links:
    - hdocker
  ports:
    - "19888:19888"
    - "8033:8033"
    - "8088:8088"
    - "8042:8042"
    - "2181:2181"
    - "11000:11000"
  expose:
    - "50070"
    - "8032"
    - "8030"
    - "8031"
    - "8040"
    - "8041"
    - "10020"
    - "10033"
slave:
  image: qurius/ubuntu-cloudera-5-slave-node:0.1
  hostname: slave
  links:
    - hdocker
    - master
  ports:
    - "50075:50075"
  expose:
    - "50010"
    - "50020"
    - "8022"
